<script lang="ts">
  const translations: { [key: string]: string } = {
    en: "Let's create something together",
    es: "Creemos algo junt@s",
    zh: "让我们一起创造一些东西",
    hi: "आइए मिलकर कुछ बनाएं",
    ar: "لنصنع شيئًا معًا",
    bn: "চলুন একসাথে কিছু তৈরি করি",
    pt: "Vamos criar algo juntos",
    ru: "Давайте создадим что-нибудь вместе",
    ja: "一緒に何かを作りましょう",
    de: "Lass uns etwas zusammen erschaffen",
    fr: "Créons quelque chose ensemble",
    it: "Creiamo qualcosa insieme",
    ko: "함께 무언가를 만들어 봐요",
    tr: "Birlikte bir şeyler yaratalım",
    vi: "Hãy cùng nhau tạo ra điều gì đó",
    pl: "Stwórzmy coś razem",
    uk: "Давайте створимо щось разом",
    nl: "Laten we samen iets maken",
    id: "Mari kita membuat sesuatu bersama",
    fa: "بیایید با هم چیزی بسازیم",
    ro: "Hai să creăm ceva împreună",
    sv: "Låt oss skapa något tillsammans",
    cs: "Pojďme společně něco vytvořit",
    el: "Ας δημιουργήσουμε κάτι μαζί",
    hu: "Alkossunk együtt valamit",
    he: "בואו ניצור משהו ביחד",
    da: "Lad os skabe noget sammen",
    fi: "Luodaan jotain yhdessä",
    no: "La oss lage noe sammen",
    sk: "Vytvorme niečo spolu",
    bg: "Нека създадем нещо заедно",
    sr: "Hajde da stvorimo nešto zajedno",
    hr: "Stvorimo nešto zajedno",
    sl: "Ustvarimo nekaj skupaj",
    et: "Loome midagi koos",
    lv: "Radīsim kaut ko kopā",
    lt: "Sukurkime ką nors kartu",
    ca: "Creem alguna cosa junts",
    eu: "Sor dezagun zerbait elkarrekin",
    gl: "Creemos algo xuntos",
    af: "Kom ons skep iets saam",
    sw: "Hebu tutengeneze kitu pamoja",
    am: "አንድ ላይ አንድ ነገር እንፍጠር",
    ta: "வாருங்கள் ஒன்றாக ஏதாவது உருவாக்குவோம்",
    te: "కలిసి ఏదైనా సృష్టిద్దాం",
    mr: "चला एकत्र काहीतरी तयार करूया",
    ur: "آئیے مل کر کچھ بنائیں",
    gu: "ચાલો સાથે મળીને કંઈક બનાવીએ",
    kn: "ಒಟ್ಟಿಗೆ ಏನಾದರೂ ರಚಿಸೋಣ",
    ml: "നമുക്ക് ഒരുമിച്ച് എന്തെങ്കിലും സൃഷ്ടിക്കാം",
    pa: "ਆਓ ਮਿਲ ਕੇ ਕੁਝ ਬਣਾਈਏ",
    ne: "सँगै केही सिर्जना गरौँ",
    si: "අපි එකට යමක් නිර්මාණය කරමු",
    my: "အတူတူ တစ်ခုခု ဖန်တီးကြရအောင်",
    km: "តោះបង្កើតអ្វីមួយជាមួយគ្នា",
    lo: "ມາສ້າງບາງສິ່ງຮ່ວມກັນ",
    th: "มาสร้างอะไรสักอย่างด้วยกัน",
    ms: "Mari kita cipta sesuatu bersama",
    tl: "Gumawa tayo ng isang bagay nang magkasama",
    ceb: "Maghimo ta og usa ka butang nga magkauban",
    jv: "Ayo nggawe sesuatu bebarengan",
    su: "Hayu urang nyieun hiji hal babarengan",
    yo: "Jẹ́ ká ṣẹ̀dá ohun kan papọ̀",
    ig: "Ka anyị mepụta ihe ọnụ",
    ha: "Mu ƙirƙiri wani abu tare",
    zu: "Masidale okuthile ndawonye",
    xh: "Masenze into kunye",
    so: "Aan wax wada abuurno",
    is: "Búum til eitthvað saman",
    ga: "Cruthaímis rud éigin le chéile",
    cy: "Gadewch i ni greu rhywbeth gyda'n gilydd",
    mt: "Ejja noħolqu xi ħaġa flimkien",
    lb: "Loosst eis eppes zesumme schafen",
    eo: "Ni kreu ion kune",
    la: "Aliquid simul creamus",
  };

  const language =
    navigator.languages
      .map((lang) => lang.toLowerCase().replace("_", "-").split("-")[0])
      .find((lang) => translations[lang!]) || "en";

  const subtitle = translations[language]!;
</script>

<span>{subtitle}</span>
